version: '3'

services:
  db:
    container_name: ${APP_NAME}-database
    image: ${DB_PROVIDER}:${DB_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks: 
      net:
        ipv4_address: ${DB_IP}
  
  www:
    build: 
      context: ./www
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${APP_NAME}-www
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    links:
      - db:mysql
    volumes:
      - ${APP_DIR}:/var/www/html:cached
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    networks:
      net:
        ipv4_address: ${WWW_IP}

  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      net:
        ipv4_address: ${PHPMYADMIN_IP}

networks: 
  net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NET_IP}

volumes:
  db_volume: